/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/BackButton/backButton.vue')['default']
    BaseLoading: typeof import('./src/components/BaseLoading/baseLoading.vue')['default']
    BottomButton: typeof import('./src/components/BottomButton/bottomButton.vue')['default']
    FilterItems: typeof import('./src/components/FilterItems/filterItems.vue')['default']
    FloatingBubble: typeof import('./src/components/FloatingBubble/floatingBubble.vue')['default']
    PromotePopup: typeof import('./src/components/PromotePopup/promotePopup.vue')['default']
    PromotionInstructions: typeof import('./src/components/PromotionInstructions/promotionInstructions.vue')['default']
    QrDialog: typeof import('./src/components/QrDialog/qrDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPopup: typeof import('./src/components/SelectPopup/selectPopup.vue')['default']
    SelectPopupV2: typeof import('./src/components/SelectPopupV2/selectPopupV2.vue')['default']
    SlideVerify: typeof import('./src/components/SlideVerify/slideVerify.vue')['default']
    TagScrollSelect: typeof import('./src/components/TagScrollSelect/tagScrollSelect.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonImage: typeof import('vant/es')['SkeletonImage']
    VanSkeletonParagraph: typeof import('vant/es')['SkeletonParagraph']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
